apiVersion: batch/v1
kind: Job
metadata:
  name: initjob
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          command:
            - sh
            - -c
            - |
              for i in 0 1 2; do
                echo "Initializing mysql-stateful-$i.mysql..."
                mysql -h mysql-stateful-$i.mysql-headless.default.svc.cluster.local -u root -p"$MYSQL_ROOT_PASSWORD" < /sql/init.sql || echo "Job failed on mysql-$i"
              done
              echo "Initializing global database table...."
              mysql -h mysql-stateful-3.mysql-headless.default.svc.cluster.local -u root -p"$MYSQL_ROOT_PASSWORD" < /sql/init-global.sql || echo "Job failed on mysql-4"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: sql-volume
              mountPath: /sql
      volumes:
        - name: sql-volume
          configMap:
            name: init-sql
      restartPolicy: Never
