apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: NGJhNjY3MTVlZGYzNGM5MzQwNjMyNjJjOWZjMjNmZDk0NzY3NTYyODY1ZTliNzdmN2JiYjE2ZGUzMDk3MGQ1Yg==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MjlmNTg3YmY0NGFkYzY4ZGY2YWM5MWMwZDUxMzA0Y2NlNzRkZDNjNGRhOWU1YzAzMWRjOTI3ZTZlMmE5ZmE1Mw==
