services:
  redis-shard-1:
    image: redis:latest
    container_name: ngs-redis-shard-1
    ports:
      - '6379:6379'
    volumes:
      - redis_data_shard_1:/data
    environment:
      - REDIS_PASSWORD=${REDIS_SHARD_1_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_SHARD_1_PASSWORD}']
    networks:
      - ngs-network
  redis-shard-2:
    image: redis:latest
    container_name: ngs-redis-shard-2
    ports:
      - '6380:6379'
    volumes:
      - redis_data_shard_2:/data
    environment:
      - REDIS_PASSWORD=${REDIS_SHARD_2_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_SHARD_2_PASSWORD}']
    networks:
      - ngs-network
  redis-shard-3:
    image: redis:latest
    container_name: ngs-redis-shard-3
    ports:
      - '6381:6379'
    volumes:
      - redis_data_shard_3:/data
    environment:
      - REDIS_PASSWORD=${REDIS_SHARD_3_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_SHARD_3_PASSWORD}']
    networks:
      - ngs-network

volumes:
  redis_data_shard_1:
  redis_data_shard_2:
  redis_data_shard_3:

networks:
  ngs-network:
    external: true
